<?php
include "../../conexion/conexion.php";

$select= $_GET['seleccion']??'0';

if($select == '0') {
    $sql = "SELECT E.CVE_ENVIO AS NENVIO, E.ENTREGADO AS ENTREGADO, C.NOMBRE AS CLIENTE, I.NOMBRE AS ITEM, EN.CANTIDAD AS CANTIDAD, I.UNIDAD AS UNIDAD, MO.NOMBRE AS MORIGEN, CO.NOMBRE AS CORIGEN, E.ORIGEN AS CALLEORIGEN, V.TIPO AS VEHICULO, V.PLACA AS PLACA, U.NOMBRE AS CONDUCTOR, U.APELLIDO_P AS CONDUCTOR1, U.APELLIDO_M AS CONDUCTOR2, MD.NOMBRE AS MDESTINO, CD.NOMBRE AS CDESTINO, E.DESTINO AS CALLEDESTINO, E.FECHASALIDA AS FECHASALIDA, E.FECHALLEGADA AS FECHALLEGADA, E.COSTO AS COSTO, E.OBSERVACIONES AS NOTA FROM items AS I JOIN encarga AS EN ON I.CVE_ITEM = EN.CVE_ITEM JOIN pedidos AS P ON EN.CVE_PEDIDO = P.CVE_PEDIDO JOIN envios AS E ON E.CVE_PEDIDO = P.CVE_PEDIDO JOIN compradores AS C ON C.CVE_COMPRADOR = P.CVE_COMPRADOR JOIN vehiculos AS V ON V.PLACA = E.PLACA JOIN usuarios AS U ON E.CVE_CONDUCTOR = U.CVE_USUARIO JOIN colonias AS CO ON CO.CVE_COLONIA = E.COLONIAORIGEN JOIN colonias AS CD ON CD.CVE_COLONIA = E.COLONIADESTINO JOIN municipios AS MO ON MO.CVE_MUNICIPIO = CO.CVE_MUNICIPIO JOIN municipios AS MD ON MD.CVE_MUNICIPIO = CD.CVE_MUNICIPIO";
} if($select == '1') {
    $sql = "SELECT E.CVE_ENVIO AS NENVIO, E.ENTREGADO AS ENTREGADO, C.NOMBRE AS CLIENTE, I.NOMBRE AS ITEM, EN.CANTIDAD AS CANTIDAD, I.UNIDAD AS UNIDAD, MO.NOMBRE AS MORIGEN, CO.NOMBRE AS CORIGEN, E.ORIGEN AS CALLEORIGEN, V.TIPO AS VEHICULO, V.PLACA AS PLACA, U.NOMBRE AS CONDUCTOR, U.APELLIDO_P AS CONDUCTOR1, U.APELLIDO_M AS CONDUCTOR2, MD.NOMBRE AS MDESTINO, CD.NOMBRE AS CDESTINO, E.DESTINO AS CALLEDESTINO, E.FECHASALIDA AS FECHASALIDA, E.FECHALLEGADA AS FECHALLEGADA, E.COSTO AS COSTO, E.OBSERVACIONES AS NOTA FROM items AS I JOIN encarga AS EN ON I.CVE_ITEM = EN.CVE_ITEM JOIN pedidos AS P ON EN.CVE_PEDIDO = P.CVE_PEDIDO JOIN envios AS E ON E.CVE_PEDIDO = P.CVE_PEDIDO JOIN compradores AS C ON C.CVE_COMPRADOR = P.CVE_COMPRADOR JOIN vehiculos AS V ON V.PLACA = E.PLACA JOIN usuarios AS U ON E.CVE_CONDUCTOR = U.CVE_USUARIO JOIN colonias AS CO ON CO.CVE_COLONIA = E.COLONIAORIGEN JOIN colonias AS CD ON CD.CVE_COLONIA = E.COLONIADESTINO JOIN municipios AS MO ON MO.CVE_MUNICIPIO = CO.CVE_MUNICIPIO JOIN municipios AS MD ON MD.CVE_MUNICIPIO = CD.CVE_MUNICIPIO WHERE E.ENTREGADO = '0'";
} if($select == '2') {
    $sql = "SELECT E.CVE_ENVIO AS NENVIO, E.ENTREGADO AS ENTREGADO, C.NOMBRE AS CLIENTE, I.NOMBRE AS ITEM, EN.CANTIDAD AS CANTIDAD, I.UNIDAD AS UNIDAD, MO.NOMBRE AS MORIGEN, CO.NOMBRE AS CORIGEN, E.ORIGEN AS CALLEORIGEN, V.TIPO AS VEHICULO, V.PLACA AS PLACA, U.NOMBRE AS CONDUCTOR, U.APELLIDO_P AS CONDUCTOR1, U.APELLIDO_M AS CONDUCTOR2, MD.NOMBRE AS MDESTINO, CD.NOMBRE AS CDESTINO, E.DESTINO AS CALLEDESTINO, E.FECHASALIDA AS FECHASALIDA, E.FECHALLEGADA AS FECHALLEGADA, E.COSTO AS COSTO, E.OBSERVACIONES AS NOTA FROM items AS I JOIN encarga AS EN ON I.CVE_ITEM = EN.CVE_ITEM JOIN pedidos AS P ON EN.CVE_PEDIDO = P.CVE_PEDIDO JOIN envios AS E ON E.CVE_PEDIDO = P.CVE_PEDIDO JOIN compradores AS C ON C.CVE_COMPRADOR = P.CVE_COMPRADOR JOIN vehiculos AS V ON V.PLACA = E.PLACA JOIN usuarios AS U ON E.CVE_CONDUCTOR = U.CVE_USUARIO JOIN colonias AS CO ON CO.CVE_COLONIA = E.COLONIAORIGEN JOIN colonias AS CD ON CD.CVE_COLONIA = E.COLONIADESTINO JOIN municipios AS MO ON MO.CVE_MUNICIPIO = CO.CVE_MUNICIPIO JOIN municipios AS MD ON MD.CVE_MUNICIPIO = CD.CVE_MUNICIPIO WHERE E.ENTREGADO = '1'";
}
    $result = $conexion->query($sql);

$envios = [];
if ($result->num_rows > 0) {
    while($row = $result->fetch_assoc()) {
        $envios[] = $row;
    }
}

foreach ($envios as &$fila) {
    if (!isset($fila['ENTREGADO']) || $fila['ENTREGADO'] === null || $fila['ENTREGADO'] == 0) {
        $fila['ENTREGADO'] = 'En transito';
    } else {
        $fila['ENTREGADO'] = 'Entregado';
    }
}

echo json_encode($envios);
?>
